package mesme;

/*
 * Provides engine definitions for MweStateEnglines
 */
public final class MweEngineDefinition {

	// state actions ought to be sourced from state engine, but just duplicated here for now
	
	public static final int ADD_TOKEN = 1;									// add current token to chunk
  public static final int CLEAR_CHUNK = 2;								// clear current chunk
  public static final int CLEAR_ADD = 12;								  // clear current chunk & add current token
  public static final int SET_MWE = 3;										// copy chunk as a MWE
  public static final int SET_MWE_CLEAR = 4;							// copy chunk as MWE and clear current chunk
  public static final int SET_MWE_ADD = 13;							  // copy chunk as MWE and add current token
  public static final int SET_MWE_ADDEMBED = 14;					// copy chunk as embedded MWE
  public static final int SET_MWE_SUBTYPE = 5;						// copy chunk as MWE, flag as a 'sub-type'
  public static final int SET_MWE_SUBTYPE_CLEAR = 6;			// copy chunk as MWE, flag as a 'sub-type', clear current chunk
  public static final int ADD_SET_MWE = 7;								// add current token, copy chunk as MWE
  public static final int ADD_SET_MWE_CLEAR = 8;					// add current token, copy chunk as MWE and clear current chunk
  public static final int ADD_SET_MWE_SUBTYPE = 9;				// add current token, copy chunk as MWE, flag as a 'sub-type'
  public static final int ADD_SET_MWE_SUBTYPE_CLEAR = 10;	// add current token, copy chunk as MWE, flag as a 'sub-type', clear current chunk
  public static final int ADD_SET_MWE_SUBTYPE_CLEAR_ADD = 15;	// add current token, copy chunk as MWE, flag as a 'sub-type', clear current chunk, add token
  public static final int ADDEMBED_CLEAR_ADD = 16;				// store current extent as potential embed for later, reset and continue
  public static final int CONTINUE = 99;									// add the token if chunk is not empty (should stay in state)
  public static final int SUBSTATE = 98;									// Switch test to earlier tag
  public static final int SKIP = 97;									    // Skip current token 
  
  public static String[] englishNominalCompounds = {
    "STOP", "JJ", "CLEAR_ADD", "ADJ", 
    "STOP", "JJR", "CLEAR_CHUNK", "INIT", 
    "STOP", "CD", "CLEAR_CHUNK", "INIT", 
    "STOP", "NN", "CLEAR_ADD", "NOUN", 
    "STOP", "NNS", "CLEAR_ADD", "NOUN", 
    "STOP", "DT", "CLEAR_CHUNK", "DTPRP",
    "STOP", "VB", "CLEAR_CHUNK", "INIT",
    "STOP", "VBD", "CLEAR_CHUNK", "INIT",
    "STOP", "VBG", "CLEAR_CHUNK", "INIT",
    "STOP", "VBN", "CLEAR_CHUNK", "INIT",
    "STOP", "VBP", "CLEAR_CHUNK", "INIT",
    "STOP", "VBZ", "CLEAR_CHUNK", "INIT",
    "STOP", "IN", "CLEAR_CHUNK", "INIT",
    "STOP", "''", "CLEAR_CHUNK", "INIT",
    "STOP", ",", "CLEAR_CHUNK", "INIT",
    "STOP", "PRP$", "CLEAR_CHUNK", "DTPRP", 
    "STOP", "PRP", "CLEAR_CHUNK", "INIT",
    "STOP", ")", "CLEAR_CHUNK", "INIT",
    "STOP", "(", "CLEAR_CHUNK", "INIT",
    "STOP", "UH", "CLEAR_CHUNK", "INIT",
    "STOP", "CC", "CLEAR_CHUNK", "CC",
    "STOP", "**", "CLEAR_CHUNK", "STOP",
    
    "INIT", "JJ", "CLEAR_ADD", "ADJ",
    "INIT", "JJR", "CLEAR_CHUNK", "ADJ", 
    "INIT", "CD", "CLEAR_CHUNK", "INIT",
    "INIT", "NN", "CLEAR_ADD", "NOUN", 
    "INIT", "NNS", "CLEAR_ADD", "NOUN",
    "INIT", "VB", "CLEAR_CHUNK", "INIT",
    "INIT", "VBD", "CLEAR_CHUNK", "INIT",
    "INIT", "VBG", "CLEAR_CHUNK", "INIT",
    "INIT", "VBN", "CLEAR_CHUNK", "INIT",
    "INIT", "VBP", "CLEAR_CHUNK", "INIT",
    "INIT", "VBZ", "CLEAR_CHUNK", "INIT",
    "INIT", "DT", "CLEAR_CHUNK", "DTPRP", 
    "INIT", "IN", "CLEAR_CHUNK", "INIT",
    "INIT", "''", "CLEAR_CHUNK", "INIT",
    "INIT", ",", "CLEAR_CHUNK", "INIT",
    "INIT", "PRP$", "CLEAR_CHUNK", "DTPRP",  
    "INIT", "PRP", "CLEAR_CHUNK", "INIT",
    "INIT", "TO", "CLEAR_CHUNK", "INIT",
    "INIT", ")", "CLEAR_CHUNK", "INIT",
    "INIT", "(", "CLEAR_CHUNK", "INIT",
    "INIT", "**", "CLEAR_CHUNK", "STOP",
   
    "DTPRP", "JJ", "CLEAR_ADD", "ADJ",
    "DTPRP", "CD", "CLEAR_CHUNK", "INIT",
    "DTPRP", "NN", "CLEAR_ADD", "NOUN", 
    "DTPRP", "NNS", "CLEAR_ADD", "NOUN", 
    "DTPRP", "VB", "CLEAR_ADD", "VERB",  
    "DTPRP", "VBD", "CLEAR_ADD", "VERB",  
    "DTPRP", "VBG", "CLEAR_ADD", "VERB",  
    "DTPRP", "VBN", "CLEAR_ADD", "VERB", 
    "DTPRP", "VBP", "CLEAR_ADD", "VERB",  
    "DTPRP", "VBZ", "CLEAR_ADD", "VERB",  
    "DTPRP", "DT", "CLEAR_CHUNK", "DTPRP",
    "DTPRP", "IN", "CLEAR_CHUNK", "INIT",
    "DTPRP", "''", "CLEAR_CHUNK", "INIT",
    "DTPRP", ",", "CLEAR_CHUNK", "INIT",
    "DTPRP", "PRP$", "CLEAR_CHUNK", "DTPRP", 
    "DTPRP", "PRP", "CLEAR_CHUNK", "INIT",
    "DTPRP", "TO", "CLEAR_CHUNK", "INIT",
    "DTPRP", ")", "CLEAR_CHUNK", "INIT",
    "DTPRP", "(", "CLEAR_CHUNK", "INIT",
    "DTPRP", "**", "CLEAR_CHUNK", "STOP",
   
    "RB", "NN", "ADD_TOKEN", "NOUN", // Not used
    "RB", "NNS", "ADD_TOKEN", "NOUN", // Not used
    "RB", "JJ", "ADD_TOKEN", "ADJ", // Not used
    "RB", "VBN", "ADD_TOKEN", "VERB", // Not used
    "RB", "**", "CLEAR_CHUNK", "STOP", // Not used
   
    "CC", "JJ", "CLEAR_ADD", "ADJ",
    "CC", "CD", "CLEAR_CHUNK", "INIT",
    "CC", "NN", "ADD_TOKEN", "NOUN", 
    "CC", "NNS", "ADD_TOKEN", "NOUN", 
    "CC", "VB", "CLEAR_CHUNK", "INIT",
    "CC", "VBD", "CLEAR_CHUNK", "INIT",
    "CC", "VBG", "CLEAR_CHUNK", "INIT",
    "CC", "VBN", "CLEAR_CHUNK", "INIT",
    "CC", "VBP", "CLEAR_CHUNK", "INIT",
    "CC", "VBZ", "CLEAR_CHUNK", "INIT",
    "CC", "DT", "CLEAR_CHUNK", "DTPRP",
    "CC", "IN", "CLEAR_CHUNK", "INIT",
    "CC", "''", "CLEAR_CHUNK", "INIT",
    "CC", ",", "CLEAR_CHUNK", "INIT",
    "CC", "PRP$", "CLEAR_CHUNK", "DTPRP",
    "CC", "PRP", "CLEAR_CHUNK", "INIT",
    "CC", "TO", "CLEAR_CHUNK", "INIT",
    "CC", ")", "CLEAR_CHUNK", "INIT",
    "CC", "(", "CLEAR_CHUNK", "INIT",
    "CC", "**", "CLEAR_CHUNK", "STOP",

    "VERB", "JJ", "ADD_TOKEN", "ADJ",
    "VERB", "CD", "CLEAR_CHUNK", "INIT",
    "VERB", "NN", "ADD_TOKEN", "NOUN", 
    "VERB", "NNS", "ADD_TOKEN", "NOUN", 
    "VERB", "VB", "CLEAR_CHUNK", "INIT",
    "VERB", "VBD", "CLEAR_CHUNK", "INIT",
    "VERB", "VBG", "CLEAR_CHUNK", "INIT",
    "VERB", "VBN", "CLEAR_CHUNK", "INIT",
    "VERB", "VBP", "CLEAR_CHUNK", "INIT",
    "VERB", "VBZ", "CLEAR_CHUNK", "INIT",
    "VERB", "DT", "CLEAR_CHUNK", "DTPRP",
    "VERB", "IN", "CLEAR_CHUNK", "INIT",
    "VERB", "''", "CLEAR_CHUNK", "INIT",
    "VERB", ",", "CLEAR_CHUNK", "INIT",
    "VERB", "PRP$", "CLEAR_CHUNK", "DTPRP",
    "VERB", "PRP", "CLEAR_CHUNK", "INIT",
    "VERB", "TO", "CLEAR_CHUNK", "INIT",
    "VERB", ")", "CLEAR_CHUNK", "INIT",
    "VERB", "(", "CLEAR_CHUNK", "INIT",
    "VERB", "**", "CLEAR_CHUNK", "STOP",

    "NOUN", "JJ", "SET_MWE_ADDEMBED", "ADJ",
    "NOUN", "NN", "ADD_TOKEN", "NOUN",
    "NOUN", "NNS", "ADD_TOKEN", "NOUN",
    "NOUN", "CC", "SET_MWE_CLEAR", "CC", 
    "NOUN", "TO", "SET_MWE_ADD", "CC",
    "NOUN", "VB", "SET_MWE_CLEAR", "INIT",
    "NOUN", "VBD", "SET_MWE_CLEAR", "INIT",
    "NOUN", "VBG", "SET_MWE_ADDEMBED", "VERB",
    "NOUN", "VBN", "SET_MWE_CLEAR", "INIT",
    "NOUN", "VBP", "SET_MWE_CLEAR", "INIT",
    "NOUN", "VBZ", "SET_MWE_CLEAR", "INIT",
    "NOUN", "DT", "SET_MWE_CLEAR", "DTPRP",
    "NOUN", "IN", "SET_MWE_CLEAR", "INIT",
    "NOUN", "''", "SET_MWE_CLEAR", "INIT",
    "NOUN", ",", "SET_MWE_CLEAR", "INIT",
    "NOUN", ".", "SET_MWE_CLEAR", "INIT",
    "NOUN", "PRP$", "SET_MWE_CLEAR", "DTPRP",
    "NOUN", "PRP", "SET_MWE_CLEAR", "INIT",
    "NOUN", "CD", "SET_MWE_CLEAR", "INIT",
    "NOUN", "TO", "SET_MWE_CLEAR", "INIT",
    "NOUN", ")", "SET_MWE_CLEAR", "INIT",
    "NOUN", "(", "SET_MWE_CLEAR", "INIT",
    "NOUN", "**", "SET_MWE_CLEAR", "STOP",
    
    "ADJ", "JJ", "CLEAR_ADD", "ADJ", 
    "ADJ", "CD", "CLEAR_CHUNK", "INIT",
    "ADJ", "NN", "ADD_TOKEN", "NOUN",
    "ADJ", "NNS", "ADD_TOKEN", "NOUN",
    "ADJ", "VB", "CLEAR_CHUNK", "INIT",
    "ADJ", "VBD", "CLEAR_CHUNK", "INIT",
    "ADJ", "VBG", "CLEAR_CHUNK", "INIT",
    "ADJ", "VBN", "CLEAR_CHUNK", "INIT",
    "ADJ", "VBP", "CLEAR_CHUNK", "INIT",
    "ADJ", "VBZ", "CLEAR_CHUNK", "INIT",
    "ADJ", "DT", "CLEAR_CHUNK", "DTPRP",
    "ADJ", "IN", "CLEAR_CHUNK", "INIT",
    "ADJ", "''", "CLEAR_CHUNK", "INIT",
    "ADJ", ",", "CLEAR_CHUNK", "INIT",
    "ADJ", "PRP$", "CLEAR_CHUNK", "DTPRP",
    "ADJ", "PRP", "CLEAR_CHUNK", "INIT",
    "ADJ", "TO", "CLEAR_CHUNK", "INIT",
    "ADJ", ")", "CLEAR_CHUNK", "INIT",
    "ADJ", "(", "CLEAR_CHUNK", "INIT",
    "ADJ", "**", "CLEAR_CHUNK", "STOP"
  };
  
// VPC engine.
  
  public static String[] englishVerbalCompounds = {
      "STOP", "VB", "CLEAR_ADD", "VERB", 
      "STOP", "VBD", "CLEAR_ADD", "VERB", 
      "STOP", "VBG", "CLEAR_ADD", "VERB", 
      "STOP", "VBN", "CLEAR_ADD", "VERB", 
      "STOP", "VBP", "CLEAR_ADD", "VERB", 
      "STOP", "VBZ", "CLEAR_ADD", "VERB", 
      "STOP", "**", "CLEAR_CHUNK", "STOP",

  		"VERB", "NN", "ADD_TOKEN", "NOUN", 
      "VERB", "NNS", "ADD_TOKEN", "NOUN",
      "VERB", "CD", "ADD_TOKEN", "NOUN",
      "VERB", "JJ", "ADD_TOKEN", "NOUN",
      "VERB", "JJR", "ADD_TOKEN", "NOUN",
      "VERB", "JJS", "ADD_TOKEN", "NOUN",
      "VERB", "VB", "CLEAR_ADD", "VERB", 
      "VERB", "VBD", "CLEAR_ADD", "VERB", 
      "VERB", "VBG", "CLEAR_ADD", "VERB", 
      "VERB", "VBN", "CLEAR_ADD", "VERB", 
      "VERB", "VBP", "CLEAR_ADD", "VERB", 
      "VERB", "VBZ", "CLEAR_ADD", "VERB", 
      "VERB", "PRP", "ADD_TOKEN", "VBPRP",
      "VERB", "PRP$", "ADD_TOKEN", "VBPRP$", 
      "VERB", "DT", "ADD_TOKEN", "VBDT", 
      "VERB", "RP", "ADD_TOKEN", "RP", 
      "VERB", "RB", "ADD_TOKEN", "RB",
      "VERB", "TO", "ADD_TOKEN", "TO",
      "VERB", "IN", "ADD_TOKEN", "IN",
      "VERB", "''", "CONTINUE", "VERB",
      "VERB", "**", "CLEAR_CHUNK", "STOP",

      "TO", ",", "SET_MWE_CLEAR", "STOP",
      "TO", ".", "SET_MWE_CLEAR", "STOP",
      "TO", "TO", "SET_MWE_CLEAR", "STOP",
      "TO", "CC", "SET_MWE_CLEAR", "STOP",
      "TO", "DT", "ADD_TOKEN", "DT",
      "TO", "PRP", "SET_MWE_ADD", "PRP",
      "TO", "VB", "CLEAR_ADD", "VERB", 
      "TO", "VBD", "CLEAR_ADD", "VERB",
      "TO", "VBG", "CLEAR_ADD", "VERB",
      "TO", "VBN", "CLEAR_ADD", "VERB",
      "TO", "VBP", "CLEAR_ADD", "VERB",
      "TO", "VBZ", "CLEAR_ADD", "VERB",
      "TO", "''", "CONTINUE", "TO",
      "TO", "**", "CLEAR_CHUNK", "STOP",

      "RP", ",", "SET_MWE_CLEAR", "STOP",
      "RP", ".", "SET_MWE_CLEAR", "STOP",
      "RP", "''", "SET_MWE_CLEAR", "STOP",
      "RP", "NN", "SET_MWE_CLEAR", "STOP",
      "RP", "NNS", "SET_MWE_CLEAR", "STOP",
      "RP", "NNP", "SET_MWE_CLEAR", "STOP",
      "RP", "RP", "SET_MWE_CLEAR", "STOP",
      "RP", "TO", "SET_MWE_CLEAR", "STOP",
      "RP", "CC", "SET_MWE_CLEAR", "STOP",
      "RP", "IN", "SET_MWE_CLEAR", "STOP",
      "RP", "UH", "SET_MWE_CLEAR", "STOP",
      "RP", "DT", "SET_MWE_ADD", "DT",  
      "RP", "PRP", "SET_MWE_ADD", "PRP",
      "RP", "PRP$", "SET_MWE_ADD", "PRP",
      "RP", "VB", "CLEAR_ADD", "VERB",
      "RP", "VBD", "CLEAR_ADD", "VERB",
      "RP", "VBG", "CLEAR_ADD", "VERB",
      "RP", "VBN", "CLEAR_ADD", "VERB",
      "RP", "VBP", "CLEAR_ADD", "VERB",
      "RP", "VBZ", "CLEAR_ADD", "VERB",
      "RP", "**", "CLEAR_CHUNK", "STOP",

      "RB", ",", "SET_MWE_CLEAR", "STOP",
      "RB", ".", "SET_MWE_CLEAR", "STOP",
      "RB", "''", "SET_MWE_CLEAR", "STOP",
      "RB", "NN", "SET_MWE_CLEAR", "STOP",
      "RB", "NNS", "SET_MWE_CLEAR", "STOP",
      "RB", "NNP", "SET_MWE_CLEAR", "STOP",
      "RB", "TO", "SET_MWE_CLEAR", "STOP",
      "RB", "CC", "SET_MWE_CLEAR", "STOP",
      "RB", "IN", "SET_MWE_CLEAR", "STOP",
      "RB", "UH", "SET_MWE_CLEAR", "STOP",
      "RB", "DT", "ADD_TOKEN", "DT",
      "RB", "PRP", "ADD_TOKEN", "PRP",
      "RB", "PRP$", "ADD_TOKEN", "PRP",
      "RB", "VB", "CLEAR_ADD", "VERB",
      "RB", "VBD", "CLEAR_ADD", "VERB",
      "RB", "VBG", "CLEAR_ADD", "VERB",
      "RB", "VBN", "CLEAR_ADD", "VERB",
      "RB", "VBP", "CLEAR_ADD", "VERB",
      "RB", "VBZ", "CLEAR_ADD", "VERB",
      "RB", "**", "CLEAR_CHUNK", "STOP",

      "IN", ",", "SET_MWE_CLEAR", "STOP",
      "IN", ".", "SET_MWE_CLEAR", "STOP",
      "IN", "''", "SET_MWE_CLEAR", "STOP",
      "IN", "RP", "SET_MWE_CLEAR", "STOP",
      "IN", "RB", "SET_MWE_CLEAR", "STOP",
      "IN", "TO", "SET_MWE_CLEAR", "STOP",
      "IN", "CC", "SET_MWE_CLEAR", "STOP",
      "IN", "IN", "SET_MWE_CLEAR", "STOP",
      "IN", "NN", "ADD_TOKEN", "NOUN", 
      "IN", "NNS", "ADD_TOKEN", "NOUN",
      "IN", "JJR", "SET_MWE_CLEAR", "STOP", 
      "IN", "DT", "ADD_TOKEN", "DT", 
      "IN", "PRP", "SKIP", "PRP",  
      "IN", "PRP$", "SKIP", "PRP", 
      "IN", "VB", "CLEAR_ADD", "VERB",
      "IN", "VBD", "CLEAR_ADD", "VERB",
      "IN", "VBG", "CLEAR_ADD", "VERB",
      "IN", "VBN", "CLEAR_ADD", "VERB",
      "IN", "VBP", "CLEAR_ADD", "VERB",
      "IN", "VBZ", "CLEAR_ADD", "VERB",
      "IN", "**", "CLEAR_CHUNK", "STOP",
 
      "DT", "NN", "ADD_TOKEN", "NOUN",
      "DT", "NNS", "ADD_TOKEN", "NOUN",
      "DT", ",", "SET_MWE_CLEAR", "STOP",
      "DT", ".", "SET_MWE_CLEAR", "STOP",
      "DT", "CC", "SET_MWE_CLEAR", "STOP",
      "DT", "VB", "CLEAR_ADD", "VERB",
      "DT", "VBD", "CLEAR_ADD", "VERB",
      "DT", "VBG", "CLEAR_ADD", "VERB",
      "DT", "VBN", "CLEAR_ADD", "VERB",
      "DT", "VBP", "CLEAR_ADD", "VERB",
      "DT", "VBZ", "CLEAR_ADD", "VERB",
      "DT", "''", "CONTINUE", "DT",
      "DT", "**", "CLEAR_CHUNK", "STOP",

      "PRP", "NN", "ADD_TOKEN", "NOUN", 
      "PRP", "NNS", "ADD_TOKEN", "NOUN", 
      "PRP", ",", "SET_MWE_CLEAR", "STOP", 
      "PRP", ".", "SET_MWE_CLEAR", "STOP",
      "PRP", "CC", "SET_MWE_CLEAR", "STOP",
      "PRP", "VB", "CLEAR_ADD", "VERB",
      "PRP", "VBD", "CLEAR_ADD", "VERB",
      "PRP", "VBG", "CLEAR_ADD", "VERB",
      "PRP", "VBN", "CLEAR_ADD", "VERB",
      "PRP", "VBP", "CLEAR_ADD", "VERB",
      "PRP", "VBZ", "CLEAR_ADD", "VERB",
      "PRP", "''", "CONTINUE", "PRP",
      "PRP", "**", "CLEAR_CHUNK", "STOP",

      "VBDT", "NN", "ADD_TOKEN", "NOUN",
      "VBDT", "NNS", "ADD_TOKEN", "NOUN",
      "VBDT", "JJ", "ADD_TOKEN", "NOUN",
      "VBDT", "JJR", "ADD_TOKEN", "NOUN",
      "VBDT", "JJS", "ADD_TOKEN", "NOUN",
      "VBDT", "VB", "CLEAR_ADD", "VERB",
      "VBDT", "VBD", "CLEAR_ADD", "VERB",
      "VBDT", "VBG", "CLEAR_ADD", "VERB",
      "VBDT", "VBN", "CLEAR_ADD", "VERB",
      "VBDT", "VBP", "CLEAR_ADD", "VERB",
      "VBDT", "VBZ", "CLEAR_ADD", "VERB",
      "VBDT", "''", "CONTINUE", "VBDT",
      "VBDT", "**", "CLEAR_CHUNK", "STOP",
   
      "NOUN", "TO", "SUBSTATE", "PRIOR",
      "NOUN", "IN", "SUBSTATE", "PRIOR",
      "NOUN", "CC", "SUBSTATE", "PRIOR",  
      "NOUN", ".", "SUBSTATE", "PRIOR",
      "NOUN", ")", "SUBSTATE", "PRIOR",
      "NOUN", "(", "SUBSTATE", "PRIOR",
      "NOUN", "NN", "ADD_TOKEN", "NOUN",
      "NOUN", "NNS", "ADD_TOKEN", "NOUN",
      "NOUN", "VB", "CLEAR_ADD", "VERB",
      "NOUN", "VBD", "CLEAR_ADD", "VERB",
      "NOUN", "VBG", "CLEAR_ADD", "VERB",
      "NOUN", "VBN", "CLEAR_ADD", "VERB",
      "NOUN", "VBP", "CLEAR_ADD", "VERB",
      "NOUN", "VBZ", "CLEAR_ADD", "VERB",
      "NOUN", "**", "CLEAR_CHUNK", "STOP",
      
      "VBPRP", "RB", "ADD_SET_MWE_CLEAR", "STOP",
      "VBPRP", "RP", "ADD_SET_MWE_CLEAR", "STOP",
      "VBPRP", "TO", "SET_MWE_CLEAR", "STOP",
      "VBPRP", "VB", "CLEAR_ADD", "VERB",
      "VBPRP", "VBD", "CLEAR_ADD", "VERB",
      "VBPRP", "VBG", "CLEAR_ADD", "VERB",
      "VBPRP", "VBN", "CLEAR_ADD", "VERB",
      "VBPRP", "VBP", "CLEAR_ADD", "VERB",
      "VBPRP", "VBZ", "CLEAR_ADD", "VERB",
      "VBPRP", "**", "CLEAR_CHUNK", "STOP",
      
      "VBPRP$", "JJ", "ADD_TOKEN", "NOUN", 
      "VBPRP$", "NN", "ADD_TOKEN", "NOUN", 
      "VBPRP$", "NNS", "ADD_TOKEN", "NOUN", 
      "VBPRP$", "VB", "CLEAR_ADD", "VERB",
      "VBPRP$", "VBD", "CLEAR_ADD", "VERB",
      "VBPRP$", "VBG", "CLEAR_ADD", "VERB",
      "VBPRP$", "VBN", "CLEAR_ADD", "VERB",
      "VBPRP$", "VBP", "CLEAR_ADD", "VERB",
      "VBPRP$", "VBZ", "CLEAR_ADD", "VERB",
      "VBPRP$", "**", "CLEAR_CHUNK", "STOP",

    // LVC SUBSTATE TEST DEFITIONS
      "PRIOR", "NN", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "NNS", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "NNP", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "VB", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "VBD", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "VBG", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "VBN", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "VBP", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "VBZ", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "TO", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "RB", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "RP", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "PRP", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "PRP$", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", "CC", "SET_MWE_SUBTYPE_CLEAR", "STOP", 
      "PRIOR", ".", "SET_MWE_SUBTYPE_CLEAR", "STOP",
      "PRIOR", ",", "SET_MWE_SUBTYPE_CLEAR", "STOP", 
      "PRIOR", "**", "CLEAR_CHUNK", "STOP",
  };
  
}
